# -*- coding: utf-8 -*-
"""config.py — 仕様書準拠のバランス定数"""
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
SAVE_DIR = os.path.join(BASE_DIR, "saves")
COMMON_PATH = os.path.join(BASE_DIR, "common_texts.json")

DAYS_IN_YEAR = 365
PREGNANCY_DAYS_TO_BIRTH = 100
CYCLE_LEN = 28

PHASES = ["morning", "afternoon", "night"]
PHASE_NAMES = {"morning": "午前", "afternoon": "午後", "night": "夜中"}

INTENSITY_NAMES = {
    "soft": "ソフト",
    "normal": "ノーマル",
    "hard": "ハード",
}

AFFECTION_SEX_MIN = 30
AFFECTION_NORMAL_OK = 30
AFFECTION_HARD_OK = 60
AFFECTION_REFUSE = 30
AFFECTION_LOVE = 71
AFFECTION_STRESS_RELIEF = 50

TRAIN_TIER_MID = 21
TRAIN_TIER_HIGH = 51

SKILL_MAX = 10
SKILL_COST_BASE = 500

JOB_PAY_MIN = 800
JOB_PAY_MAX = 1500

# 触手調教（受胎度）
TENTACLE_TRAIN_STRESS = (18, 22)
TENTACLE_TRAIN_STAMINA = (14, 20)
TENTACLE_CONCEPTION_GAIN = (8, 15)
TENTACLE_STRESS_REDUCE_PER_LV = 0.12   # 女の子の開発Lv
TENTACLE_STAMINA_REDUCE_PER_LV = 0.10
TENTACLE_STRESS_FLOOR = 6
TENTACLE_STAMINA_FLOOR = 8

# 触手レベル（館）
TENTACLE_LEVEL_INIT = 1
TENTACLE_LEVEL_MAX = 10
TENTACLE_LEVEL_DUAL = 6          # 以上で2本
TENTACLE_LEVEL_STRESS_PER = 0.15  # (lv-1) * この倍率を基本に加算
TENTACLE_LEVEL_STAMINA_PER = 0.10
TENTACLE_DUAL_MULT = 1.4         # 2本時の追加倍率

# 因子
PLAYER_FACTOR_MAX = 100
PLAYER_WITCH_BASE_PCT = 2.0
PLAYER_WITCH_PER_FACTOR = 0.30
MEDITATE_FACTOR_GAIN = (1, 10)
EXTRACT_FACTOR_GAIN = (10, 20)

SEX_STAMINA = (12, 18)
SEX_STAMINA_REDUCE_PER_LV = 0.08
SEX_STAMINA_FLOOR = 6

CONCEPTION_WITCH_READY = 100
INFIRMARY_FROM_DAY = 95

# 仲良しのストレス軽減（触手1回を2回で相殺しない）
BOND_STRESS_DOWN = (4, 8)
